version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_HOST: db
      DB_DIALECT: mariadb
      DB_PORT: 3306
      DB_NAME: dsbdb
      DB_USER: root
      DB_PASSWORD: root
      BUCKET_HOST: minio
      BUCKET_PORT: 9000
      BUCKET_ACCESS_KEY: minioadmin
      BUCKET_ACCESS_SECRET: minioadminpw
      BUCKET_NAME_FILES: files
      LOCALFILES_FILEPATH: images/
    ports:
      - "8080:8080"
    networks:
      - app
    depends_on:
      - db
      - minio

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dsbdb
      MYSQL_USER: dsbuser
      MYSQL_PASSWORD: dsbuserpw
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

  minio:
    image: bitnami/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpw
      MINIO_DEFAULT_BUCKETS: "pictures,files"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - app

volumes:
  db-data:
  minio:

networks:
  app:
