INSERT INTO dsbdb.roles (name) VALUES ('ROLE_STUDENT');
INSERT INTO dsbdb.roles (name) VALUES ('ROLE_INSTRUCTOR');
INSERT INTO dsbdb.roles (name) VALUES ('ROLE_ADMIN');

INSERT INTO dsbdb.country (name) VALUES ('Austria');

INSERT INTO dsbdb.country (name) VALUES ('Afghanistan');
INSERT INTO dsbdb.country (name) VALUES ('Albania');
INSERT INTO dsbdb.country (name) VALUES ('Algeria');
INSERT INTO dsbdb.country (name) VALUES ('Andorra');
INSERT INTO dsbdb.country (name) VALUES ('Angola');
INSERT INTO dsbdb.country (name) VALUES ('Antigua and Barbuda');
INSERT INTO dsbdb.country (name) VALUES ('Argentina');
INSERT INTO dsbdb.country (name) VALUES ('Armenia');
INSERT INTO dsbdb.country (name) VALUES ('Australia');

INSERT INTO dsbdb.country (name) VALUES ('Azerbaijan');
INSERT INTO dsbdb.country (name) VALUES ('Bahamas');
INSERT INTO dsbdb.country (name) VALUES ('Bahrain');
INSERT INTO dsbdb.country (name) VALUES ('Bangladesh');
INSERT INTO dsbdb.country (name) VALUES ('Barbados');
INSERT INTO dsbdb.country (name) VALUES ('Belarus');
INSERT INTO dsbdb.country (name) VALUES ('Belgium');
INSERT INTO dsbdb.country (name) VALUES ('Belize');
INSERT INTO dsbdb.country (name) VALUES ('Benin');
INSERT INTO dsbdb.country (name) VALUES ('Bhutan');
INSERT INTO dsbdb.country (name) VALUES ('Bolivia');
INSERT INTO dsbdb.country (name) VALUES ('Bosnia and Herzegovina');
INSERT INTO dsbdb.country (name) VALUES ('Botswana');
INSERT INTO dsbdb.country (name) VALUES ('Brazil');
INSERT INTO dsbdb.country (name) VALUES ('Brunei');
INSERT INTO dsbdb.country (name) VALUES ('Bulgaria');
INSERT INTO dsbdb.country (name) VALUES ('Burkina Faso');
INSERT INTO dsbdb.country (name) VALUES ('Burundi');
INSERT INTO dsbdb.country (name) VALUES ('Cabo Verde');
INSERT INTO dsbdb.country (name) VALUES ('Cambodia');
INSERT INTO dsbdb.country (name) VALUES ('Cameroon');
INSERT INTO dsbdb.country (name) VALUES ('Canada');
INSERT INTO dsbdb.country (name) VALUES ('Central African Republic');
INSERT INTO dsbdb.country (name) VALUES ('Chad');
INSERT INTO dsbdb.country (name) VALUES ('Chile');
INSERT INTO dsbdb.country (name) VALUES ('China');
INSERT INTO dsbdb.country (name) VALUES ('Colombia');
INSERT INTO dsbdb.country (name) VALUES ('Comoros');
INSERT INTO dsbdb.country (name) VALUES ('Congo, Democratic Republic of the');
INSERT INTO dsbdb.country (name) VALUES ('Congo, Republic of the');
INSERT INTO dsbdb.country (name) VALUES ('Costa Rica');
INSERT INTO dsbdb.country (name) VALUES ('Croatia');
INSERT INTO dsbdb.country (name) VALUES ('Cuba');
INSERT INTO dsbdb.country (name) VALUES ('Cyprus');
INSERT INTO dsbdb.country (name) VALUES ('Czech Republic');
INSERT INTO dsbdb.country (name) VALUES ('Denmark');
INSERT INTO dsbdb.country (name) VALUES ('Djibouti');
INSERT INTO dsbdb.country (name) VALUES ('Dominica');
INSERT INTO dsbdb.country (name) VALUES ('Dominican Republic');
INSERT INTO dsbdb.country (name) VALUES ('Ecuador');
INSERT INTO dsbdb.country (name) VALUES ('Egypt');
INSERT INTO dsbdb.country (name) VALUES ('El Salvador');
INSERT INTO dsbdb.country (name) VALUES ('Equatorial Guinea');
INSERT INTO dsbdb.country (name) VALUES ('Eritrea');
INSERT INTO dsbdb.country (name) VALUES ('Estonia');
INSERT INTO dsbdb.country (name) VALUES ('Eswatini');
INSERT INTO dsbdb.country (name) VALUES ('Ethiopia');
INSERT INTO dsbdb.country (name) VALUES ('Fiji');
INSERT INTO dsbdb.country (name) VALUES ('Finland');
INSERT INTO dsbdb.country (name) VALUES ('France');
INSERT INTO dsbdb.country (name) VALUES ('Gabon');
INSERT INTO dsbdb.country (name) VALUES ('Gambia');
INSERT INTO dsbdb.country (name) VALUES ('Georgia');
INSERT INTO dsbdb.country (name) VALUES ('Germany');
INSERT INTO dsbdb.country (name) VALUES ('Ghana');
INSERT INTO dsbdb.country (name) VALUES ('Greece');
INSERT INTO dsbdb.country (name) VALUES ('Grenada');
INSERT INTO dsbdb.country (name) VALUES ('Guatemala');
INSERT INTO dsbdb.country (name) VALUES ('Guinea');
INSERT INTO dsbdb.country (name) VALUES ('Guinea-Bissau');
INSERT INTO dsbdb.country (name) VALUES ('Guyana');
INSERT INTO dsbdb.country (name) VALUES ('Haiti');
INSERT INTO dsbdb.country (name) VALUES ('Honduras');
INSERT INTO dsbdb.country (name) VALUES ('Hungary');
INSERT INTO dsbdb.country (name) VALUES ('Iceland');
INSERT INTO dsbdb.country (name) VALUES ('India');
INSERT INTO dsbdb.country (name) VALUES ('Indonesia');
INSERT INTO dsbdb.country (name) VALUES ('Iran');
INSERT INTO dsbdb.country (name) VALUES ('Iraq');
INSERT INTO dsbdb.country (name) VALUES ('Ireland');
INSERT INTO dsbdb.country (name) VALUES ('Israel');
INSERT INTO dsbdb.country (name) VALUES ('Italy');
INSERT INTO dsbdb.country (name) VALUES ('Jamaica');
INSERT INTO dsbdb.country (name) VALUES ('Japan');
INSERT INTO dsbdb.country (name) VALUES ('Jordan');
INSERT INTO dsbdb.country (name) VALUES ('Kazakhstan');
INSERT INTO dsbdb.country (name) VALUES ('Kenya');
INSERT INTO dsbdb.country (name) VALUES ('Kiribati');
INSERT INTO dsbdb.country (name) VALUES ('Kuwait');
INSERT INTO dsbdb.country (name) VALUES ('Kyrgyzstan');
INSERT INTO dsbdb.country (name) VALUES ('Laos');
INSERT INTO dsbdb.country (name) VALUES ('Latvia');
INSERT INTO dsbdb.country (name) VALUES ('Lebanon');
INSERT INTO dsbdb.country (name) VALUES ('Lesotho');
INSERT INTO dsbdb.country (name) VALUES ('Liberia');
INSERT INTO dsbdb.country (name) VALUES ('Libya');
INSERT INTO dsbdb.country (name) VALUES ('Liechtenstein');
INSERT INTO dsbdb.country (name) VALUES ('Lithuania');
INSERT INTO dsbdb.country (name) VALUES ('Luxembourg');
INSERT INTO dsbdb.country (name) VALUES ('Madagascar');
INSERT INTO dsbdb.country (name) VALUES ('Malawi');
INSERT INTO dsbdb.country (name) VALUES ('Malaysia');
INSERT INTO dsbdb.country (name) VALUES ('Maldives');
INSERT INTO dsbdb.country (name) VALUES ('Mali');
INSERT INTO dsbdb.country (name) VALUES ('Malta');
INSERT INTO dsbdb.country (name) VALUES ('Marshall Islands');
INSERT INTO dsbdb.country (name) VALUES ('Mauritania');
INSERT INTO dsbdb.country (name) VALUES ('Mauritius');
INSERT INTO dsbdb.country (name) VALUES ('Mexico');
INSERT INTO dsbdb.country (name) VALUES ('Micronesia');
INSERT INTO dsbdb.country (name) VALUES ('Moldova');
INSERT INTO dsbdb.country (name) VALUES ('Monaco');
INSERT INTO dsbdb.country (name) VALUES ('Mongolia');
INSERT INTO dsbdb.country (name) VALUES ('Montenegro');
INSERT INTO dsbdb.country (name) VALUES ('Morocco');
INSERT INTO dsbdb.country (name) VALUES ('Mozambique');
INSERT INTO dsbdb.country (name) VALUES ('Myanmar');
INSERT INTO dsbdb.country (name) VALUES ('Namibia');
INSERT INTO dsbdb.country (name) VALUES ('Nauru');
INSERT INTO dsbdb.country (name) VALUES ('Nepal');
INSERT INTO dsbdb.country (name) VALUES ('Netherlands');
INSERT INTO dsbdb.country (name) VALUES ('New Zealand');
INSERT INTO dsbdb.country (name) VALUES ('Nicaragua');
INSERT INTO dsbdb.country (name) VALUES ('Niger');
INSERT INTO dsbdb.country (name) VALUES ('Nigeria');
INSERT INTO dsbdb.country (name) VALUES ('North Korea');
INSERT INTO dsbdb.country (name) VALUES ('North Macedonia');
INSERT INTO dsbdb.country (name) VALUES ('Norway');
INSERT INTO dsbdb.country (name) VALUES ('Oman');
INSERT INTO dsbdb.country (name) VALUES ('Pakistan');
INSERT INTO dsbdb.country (name) VALUES ('Palau');
INSERT INTO dsbdb.country (name) VALUES ('Panama');
INSERT INTO dsbdb.country (name) VALUES ('Papua New Guinea');
INSERT INTO dsbdb.country (name) VALUES ('Paraguay');
INSERT INTO dsbdb.country (name) VALUES ('Peru');
INSERT INTO dsbdb.country (name) VALUES ('Philippines');
INSERT INTO dsbdb.country (name) VALUES ('Poland');
INSERT INTO dsbdb.country (name) VALUES ('Portugal');
INSERT INTO dsbdb.country (name) VALUES ('Qatar');
INSERT INTO dsbdb.country (name) VALUES ('Romania');
INSERT INTO dsbdb.country (name) VALUES ('Russia');
INSERT INTO dsbdb.country (name) VALUES ('Rwanda');
INSERT INTO dsbdb.country (name) VALUES ('Saint Kitts and Nevis');
INSERT INTO dsbdb.country (name) VALUES ('Saint Lucia');
INSERT INTO dsbdb.country (name) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO dsbdb.country (name) VALUES ('Samoa');
INSERT INTO dsbdb.country (name) VALUES ('San Marino');
INSERT INTO dsbdb.country (name) VALUES ('Sao Tome and Principe');
INSERT INTO dsbdb.country (name) VALUES ('Saudi Arabia');
INSERT INTO dsbdb.country (name) VALUES ('Senegal');
INSERT INTO dsbdb.country (name) VALUES ('Serbia');
INSERT INTO dsbdb.country (name) VALUES ('Seychelles');
INSERT INTO dsbdb.country (name) VALUES ('Sierra Leone');
INSERT INTO dsbdb.country (name) VALUES ('Singapore');
INSERT INTO dsbdb.country (name) VALUES ('Slovakia');
INSERT INTO dsbdb.country (name) VALUES ('Slovenia');
INSERT INTO dsbdb.country (name) VALUES ('Solomon Islands');
INSERT INTO dsbdb.country (name) VALUES ('Somalia');
INSERT INTO dsbdb.country (name) VALUES ('South Africa');
INSERT INTO dsbdb.country (name) VALUES ('South Korea');
INSERT INTO dsbdb.country (name) VALUES ('South Sudan');
INSERT INTO dsbdb.country (name) VALUES ('Spain');
INSERT INTO dsbdb.country (name) VALUES ('Sri Lanka');
INSERT INTO dsbdb.country (name) VALUES ('Sudan');
INSERT INTO dsbdb.country (name) VALUES ('Suriname');
INSERT INTO dsbdb.country (name) VALUES ('Sweden');
INSERT INTO dsbdb.country (name) VALUES ('Switzerland');
INSERT INTO dsbdb.country (name) VALUES ('Syria');
INSERT INTO dsbdb.country (name) VALUES ('Taiwan');
INSERT INTO dsbdb.country (name) VALUES ('Tajikistan');
INSERT INTO dsbdb.country (name) VALUES ('Tanzania');
INSERT INTO dsbdb.country (name) VALUES ('Thailand');
INSERT INTO dsbdb.country (name) VALUES ('Timor-Leste');
INSERT INTO dsbdb.country (name) VALUES ('Togo');
INSERT INTO dsbdb.country (name) VALUES ('Tonga');
INSERT INTO dsbdb.country (name) VALUES ('Trinidad and Tobago');
INSERT INTO dsbdb.country (name) VALUES ('Tunisia');
INSERT INTO dsbdb.country (name) VALUES ('Turkey');
INSERT INTO dsbdb.country (name) VALUES ('Turkmenistan');
INSERT INTO dsbdb.country (name) VALUES ('Tuvalu');
INSERT INTO dsbdb.country (name) VALUES ('Uganda');
INSERT INTO dsbdb.country (name) VALUES ('Ukraine');
INSERT INTO dsbdb.country (name) VALUES ('United Arab Emirates');
INSERT INTO dsbdb.country (name) VALUES ('United Kingdom');
INSERT INTO dsbdb.country (name) VALUES ('United States of America');
INSERT INTO dsbdb.country (name) VALUES ('Uruguay');
INSERT INTO dsbdb.country (name) VALUES ('Uzbekistan');
INSERT INTO dsbdb.country (name) VALUES ('Vanuatu');
INSERT INTO dsbdb.country (name) VALUES ('Vatican City');
INSERT INTO dsbdb.country (name) VALUES ('Venezuela');
INSERT INTO dsbdb.country (name) VALUES ('Vietnam');
INSERT INTO dsbdb.country (name) VALUES ('Yemen');
INSERT INTO dsbdb.country (name) VALUES ('Zambia');
INSERT INTO dsbdb.country (name) VALUES ('Zimbabwe');