name: docker-build

on:
  push:
    branches:
      - "master"
      - "14-security-setup"
      -  "div1.1"
      - "country_feature"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: driving/app:latest
          cache-from: type=registry,ref=driving/app:latest
          cache-to: type=inline